### ISSUE TITLE
bug: Cannot read property 'clientY' of undefined

### ISSUE THREAD

**Issue by cherish1260** [tuax/tua-body-scroll-lock#33]
Version 1.0.0

ios 11 

error: Cannot read property 'clientY' of undefined

HTMLDivElement.i.ios.f.indexOf.e.ontouchstart()

**Comment by BuptStEve** [comment]
额，能不能按照 issue 模板填一下？有中文版的...

**Comment by cherish1260** [comment]
> 额，能不能按照 issue 模板填一下？有中文版的...

使用版本：1.0.0

系统版本：ios 11

发现报错：

**Comment by BuptStEve** [comment]
![image](https://user-images.githubusercontent.com/11501493/70877620-25d11a80-1ff9-11ea-8d61-9855a72030ec.png)

建议 **fork** 以下某个平台的 demo 复现一下：

* jsbin: https://jsbin.com/cafiful/edit?output
* codepen: https://codepen.io/buptsteve/pen/PvNQjP
* jsfiddle: https://jsfiddle.net/buptsteve/6u8g3Lf5/
* codesandbox: https://codesandbox.io/s/o73z4jy5q9

demo 就报错了么？

**Comment by cherish1260** [comment]
> ![image](https://user-images.githubusercontent.com/11501493/70877620-25d11a80-1ff9-11ea-8d61-9855a72030ec.png)
> 
> 建议 **fork** 以下某个平台的 demo 复现一下：
> 
> * jsbin: https://jsbin.com/cafiful/edit?output
> * codepen: https://codepen.io/buptsteve/pen/PvNQjP
> * jsfiddle: https://jsfiddle.net/buptsteve/6u8g3Lf5/
> * codesandbox: https://codesandbox.io/s/o73z4jy5q9
> 
> demo 就报错了么？

因为目前项目里使用了报错统计，目前能看到的是在ios11上会报clientY' of undefined的错；

定位到是在
`targetElement.ontouchstart = (event) => {
                initialClientY = event.targetTouches[0].clientY;
                initialClientX = event.targetTouches[0].clientX;
            };`
这里在获取clientY时报的错

**Comment by BuptStEve** [comment]
哦哦，就是偶现的咯？

**Comment by cherish1260** [comment]
> 哦哦，就是偶现的咯？
目前看，只要是ios11版本的都会报错，其他的是好使的

**Comment by evinma** [comment]
辛苦给一个可以复现问题的版本，我这里用demo页测试没发现报错。 
测试ios版本: 11.0.2
 fork 以下某个平台的 demo 复现一下：
- jsbin: https://jsbin.com/cafiful/edit?output
- codepen: https://codepen.io/buptsteve/pen/PvNQjP
- jsfiddle: https://jsfiddle.net/buptsteve/6u8g3Lf5/
- codesandbox: https://codesandbox.io/s/o73z4jy5q9
@cherish1260
