### ISSUE TITLE
safari浏览器 当工具栏收起时 滑动手机下方 依然有滑动穿透

### ISSUE THREAD

**Issue by chendong-xie** [tuax/tua-body-scroll-lock#57]
**版本**
Version [v1.1.0]

**描述一下 bug**
safari浏览器 当工具栏收起时 滑动手机下方 依然有滑动穿透

https://user-images.githubusercontent.com/82069123/122050654-3f356b80-ce16-11eb-95e2-9545691ac09e.mp4

视频中最后滑动的位置为手机的下方

**Comment by BuptStEve** [comment]
你咋操作的？拿另一个手机拍一下？
我用 iPhone 7p 没复现...

**Comment by chendong-xie** [comment]
@BuptStEve 满足两点就可以：
1、safari浏览器（我的手机是iphone XR）
2、在页面的下方滑动

**Comment by Xuchuzhi** [comment]
![image](https://user-images.githubusercontent.com/33823300/147080167-9476a097-7f75-453f-b5c9-f9d9c43a991f.png)
event.cancelable 是 true
iphone12重现
感觉可以在event自定义一个变量控制

**Comment by BuptStEve** [comment]
![023acabd-52a4-409b-8655-217f5b8b3e46](https://user-images.githubusercontent.com/11501493/147196950-fae4b5aa-f394-4a9f-8180-408b313d6560.gif)

**Comment by BuptStEve** [comment]
我复现了，我感觉是浏览器的正常行为，而且这个也不是很常见的场景，维持现状挺好的。
