### ISSUE TITLE
bug: lock fails with native dialog modal

### ISSUE THREAD

**Issue by milan338** [tuax/tua-body-scroll-lock#59]
**Version**
1.2.1

**Describe the bug**
When attempting to lock scroll on showing a native dialog modal, it is still possible to scroll the content behind the modal.

**To Reproduce**
1. Create an HTML `dialog` element
2. Call `dialog.showModal()`
3. Call `lock(dialogRef)`
4. Attempt to scroll

**Expected behavior**
The content should not scroll behind the modal after `lock` is called.

**Additional context**
Replacing `$body` from `document.body` with `document.documentElement` fixes the issue in `setOverflowHiddenPc`.

**Comment by milan338** [comment]
I looked into this a bit more, and I found that the reason this was happening in my case was the root HTML element itself was scrolling due to some weird styling. [Here's](https://codesandbox.io/s/tua-body-scroll-lock-html-scroll-bug-3xyhj3) a codesandbox that shows this issue.

**Comment by BuptStEve** [comment]
> I looked into this a bit more, and I found that the reason this was happening in my case was the root HTML element itself was scrolling due to some weird styling. [Here's](https://codesandbox.io/s/tua-body-scroll-lock-html-scroll-bug-3xyhj3) a codesandbox that shows this issue.

Because of this?
<img width="1363" alt="image" src="https://github.com/tuax/tua-body-scroll-lock/assets/11501493/a1c5b2a3-ceb4-414d-b7f3-52dda5400891">

**Comment by milan338** [comment]
> It's working~ https://codesandbox.io/s/tua-body-scroll-lock-html-scroll-bug-forked-6x9p7m?file=/src/index.js

The scroll doesn't get locked for me, I'm still able to scroll the background.

**Comment by BuptStEve** [comment]
> > It's working~ https://codesandbox.io/s/tua-body-scroll-lock-html-scroll-bug-forked-6x9p7m?file=/src/index.js
> 
> The scroll doesn't get locked for me, I'm still able to scroll the background.

You mean the mouse scrolling?
This lib is more for mobile scenario. 😄

**Comment by BuptStEve** [comment]
I get it~
I'll fix it.
