### ISSUE TITLE
bug: Broken reversed scrollbar on desktop

### ISSUE THREAD

**Issue by kyrylo-soulandwolf** [tuax/tua-body-scroll-lock#62]
**Version**
Version 1.3.0

**Describe the bug**
After updating to 1.3.0 `padding-right` on `html` gets set to 0 on desktop.

Providing a reproduction demo will be better (you can pick a platform below and **fork** the demo):
* codepen: https://codepen.io/kyrylo-soulandwolf/pen/MWzQYwK

**Expected behaviour**
Padding is to be set on `html` to reverse the width of the scroll bar.

**Comment by BuptStEve** [comment]
All right, maybe we can provide an option...

**Comment by kyrylo-soulandwolf** [comment]
> Hi @kyrylo-soulandwolf how about this one: https://codesandbox.io/s/issue-62-hv7cf4?file=/src/index.js

Hey @BuptStEve 
Looks good, this demo seems to fix the issue :)
