### ISSUE TITLE
The `body-scroll-lock` demo calls the wrong methods

### ISSUE THREAD

**Issue by claus** [tuax/tua-body-scroll-lock#67]
```js
btn.onclick = function() {
  modalOne.style.display = 'block'
  bodyScrollLock.enableBodyScroll(targetOne)
}
modalBtn.onclick = function() {
  modalTwo.style.display = 'block'
  bodyScrollLock.enableBodyScroll(targetTwo)
}
```

If you call `disableBodyScroll` instead of `enableBodyScroll`, you'll find that the [`body-scroll-lock` demo](https://codepen.io/buptsteve/pen/EJoKQK) works just fine with the original package.

**Comment by BuptStEve** [comment]
https://codepen.io/buptsteve-the-encoder/pen/RwqEqKL
emmm, still some bugs...
## 1. iOS scroll to top
https://github.com/tuax/tua-body-scroll-lock/assets/11501493/70036ace-74da-4ec9-a044-25b5d1ae6f20

## 2. enableBodyScroll for all
https://github.com/tuax/tua-body-scroll-lock/assets/11501493/cfd6ee7c-ab2c-4d5d-aa35-356e05bc4f12

**Comment by claus** [comment]
Regarding the scroll-to-top bug, that's actually not a bug in the code, but a broken ESM build. Try grabbing the code from `body-scroll-lock` and putting it directly into your app and import from there, and you'll see it magically starts working.

**Comment by BuptStEve** [comment]
> Regarding the scroll-to-top bug, that's actually not a bug in the code, but a broken ESM build. Try grabbing the code from `body-scroll-lock` and putting it directly into your app and import from there, and you'll see it magically starts working.

I mean when i call `enableBodyScroll` by **modalTwo**, the body scroll lock is disabled, which was locked by modalOne.

**Comment by claus** [comment]
Oh gotcha, my bad!
