### ISSUE TITLE
Use one state for multiple instances

### ISSUE THREAD

**Issue by deevanych** [tuax/tua-body-scroll-lock#72]
**Is your feature request related to a problem? Please describe.**
I wrote a plugin (needed at work) that I embed on websites. This plugin uses BSL. And the sites that use this plugin also use BSL. The problem is that inside the plugin, the lock/unlock functions use their lockedElements, lockedNum and the same on the site. That is, if you close all the windows in the plugin, but there are open ones on the site, the plugin will execute unLockCallback() because it does not know that there are open popups on the site.

**Describe the solution you'd like**
Use window.bsl object for statement. In this case all instances BSL will has access to lockedElements and lockedNum.

**Describe alternatives you've considered**
// empty

**Additional context**
// empty

**Comment by BuptStEve** [comment]
It's a good idea~

**Comment by deevanych** [comment]
> It's a good idea~

Can I do it myself?

**Comment by BuptStEve** [comment]
> > It's a good idea~
> 
> Can I do it myself?

PR welcome

**Comment by BuptStEve** [comment]
@deevanych done~
