### ISSUE TITLE
bug: uninitialized target elements break

### ISSUE THREAD

**Issue by hustlelikeaboss** [tuax/tua-body-scroll-lock#80]
**Version**
Version 1.5.0

**Describe the bug**
If a provided target element, for whatever reason, is not yet initialized when `lock` is called, it breaks.
<img width="1140" alt="Screenshot 2024-10-23 at 11 05 02 AM" src="https://github.com/user-attachments/assets/1017504b-9637-49fe-8657-5e352a70ce1b">

**Expected behavior**
It should exit/fail gracefully by accounting for undefined elements in the filtering logic.

**Additional context**
this only occurs on iOS devices.

**Comment by BuptStEve** [comment]
@all-contributors add @hustlelikeaboss  for bug
